usr/include/ignition/rendering[0-99]/ignition/rendering/ogre/*
usr/include/ignition/rendering[0-99]/ignition/rendering/ogre.hh
usr/lib/*/libignition-rendering[0-99]-ogre.so
usr/lib/*/pkgconfig/ignition-rendering[0-99]-ogre.pc
usr/lib/*/cmake/ignition-rendering[0-99]-ogre/*
usr/lib/*/ign-rendering-[0-99]/engine-plugins/libignition-rendering*-ogre.so
usr/share/ignition/ignition-rendering[0-99]/ogre/*
